const JobsActionTypes = {
  FETCH_JOBS_START: "FETCH_JOBS_START",
  FETCH_JOB_START: "FETCH_JOB_START",
  FETCH_JOBS_SUCCESS: "FETCH_JOBS_SUCCESS",
  FETCH_JOB_SUCCESS: "FETCH_JOB_SUCCESS",
  FETCH_JOBS_FAILURE: "FETCH_JOBS_FAILURE",
  FETCH_JOB_FAILURE: "FETCH_JOB_FAILURE",
  UPDATE_HAS_NEXT_PAGE: "UPDATE_HAS_NEXT_PAGE",
  CLEAR_JOBS: "CLEAR_JOBS",
};

export default JobsActionTypes;
